In [1]:
# importing necessary Libraries

import pandas as pd
from pathlib import Path


# finding path of the folder

current_folder = Path.cwd()
print(current_folder)

C:\Users\Dell\Nexatel_project


In [2]:
data_folder = Path.cwd()

In [3]:
# checking all csv files

csv_files = sorted(data_folder.glob("*.csv"))
print("Number of csv files:",len(csv_files))

for file in csv_files:
    print(file.name)

Number of csv files: 24
billing.csv
cities.csv
complaints.csv
contracts.csv
customer_feedback.csv
customers.csv
data_quality_issue_log.csv
devices.csv
employees.csv
marketing_campaigns.csv
network_quality.csv
payments.csv
plan_history.csv
plans.csv
recharges.csv
regions.csv
retention_campaigns.csv
states.csv
stores.csv
subscriptions.csv
support_tickets.csv
usage_data.csv
usage_sms.csv
usage_voice.csv


In [4]:
# creating a empty dictionary
all_dfs = {}



#Loading all csv files

for file in csv_files:
    table_name = file.stem

    all_dfs[table_name] = pd.read_csv(file,low_memory=False)
    print(table_name,all_dfs[table_name].shape)



billing (115313, 9)
cities (68, 8)
complaints (16584, 7)
contracts (10607, 9)
customer_feedback (28499, 7)
customers (19076, 25)
data_quality_issue_log (20, 3)
devices (19000, 8)
employees (800, 9)
marketing_campaigns (40, 9)
network_quality (57000, 8)
payments (92362, 7)
plan_history (19349, 6)
plans (25, 10)
recharges (146501, 6)
regions (4, 3)
retention_campaigns (6475, 8)
states (36, 4)
stores (2180, 7)
subscriptions (20523, 8)
support_tickets (31490, 11)
usage_data (57000, 5)
usage_sms (57000, 5)
usage_voice (57000, 6)


In [5]:
# checking all files loaded

print("tatal loaded table:",len(all_dfs))

tatal loaded table: 24


In [6]:
print(all_dfs.keys())

dict_keys(['billing', 'cities', 'complaints', 'contracts', 'customer_feedback', 'customers', 'data_quality_issue_log', 'devices', 'employees', 'marketing_campaigns', 'network_quality', 'payments', 'plan_history', 'plans', 'recharges', 'regions', 'retention_campaigns', 'states', 'stores', 'subscriptions', 'support_tickets', 'usage_data', 'usage_sms', 'usage_voice'])


In [7]:
# checking first five rows

all_dfs["customers"].head()

,customer_id,first_name,last_name,gender,date_of_birth,age,email,phone_number,address,city_id,...,occupation,annual_income_inr,customer_segment,product_line,plan_id,acquisition_channel,acquisition_date,tenure_months,customer_status,churn_date
0,C0000001,Harish,Shetty,Male,31-03-1988,38,harish.shetty909@yahoo.in,916647481156,"Plot 382, Tilak Lane, Raipur",CT0026,...,School Teacher,791058.0,Mass,Prepaid Mobile,PL002,Retail Store,15-01-2026,2,Churned,22-03-2026
1,C0000002,Anjali,Khan,Female,31-03-1974,52,anjali.khan525@rediffmail.com,918116536619,"Door No. 269, Civil Lines Colony, Gurugram",CT0009,...,Small Business Owner,1385499.0,Premium,Fiber Broadband,PL017,Retail Store,01-01-2014,146,Active,NaN
2,C0000003,Arjun,Hegde,Male,31-03-1978,48,arjun.hegde378@hotmail.com,918958153134,"House No. 320, Garden Nagar, Vadodara",CT0020,...,Auto/Cab Driver,394773.0,Enterprise,Enterprise,PL021,Tele-sales,11-11-2015,1,Churned,22-12-2015
3,C0000004,Vidya,Parmar,Female,31-03-1988,38,vidya.parmar387@hotmail.com,917763920098,"House No. 204, Industrial Street, Nagpur",CT0015,...,Operations Manager,1977532.0,Premium,Prepaid Mobile,PL006,Tele-sales,2014/10/18,137,Active,NaN
4,C0000005,Arjun,Saxena,Male,31-03-1988,38,arjun.saxena410@yahoo.in,916787478273,"Flat 156, Krishna Sector, Warangal",CT0043,...,Retired,847300.0,Value,Prepaid Mobile,PL003,Online,20-10-2014,108,Churned,22-10-2023


In [8]:
#checking column & rows

all_dfs["customers"].shape

(19076, 25)

In [9]:
# Profiling the database

df = all_dfs["customers"]
print("table_name: customers")
print("row_count:", df.shape[0])
print("column_count:", df.shape[1])
print("Data_types:")
print(df.dtypes)

table_name: customers
row_count: 19076
column_count: 25
Data_types:
customer_id             object
first_name              object
last_name               object
gender                  object
date_of_birth           object
age                      int64
email                   object
phone_number             int64
address                 object
city_id                 object
city_name               object
state_id                object
pin_code                 int64
city_tier               object
region_id               object
occupation              object
annual_income_inr      float64
customer_segment        object
product_line            object
plan_id                 object
acquisition_channel     object
acquisition_date        object
tenure_months            int64
customer_status         object
churn_date              object
dtype: object


In [10]:
#profiling all table in one go
#finding Rows
# finding column
# finding data type


for table_name,df in all_dfs.items():
    print("Table:",table_name)
    print("Row_count",df.shape[0])
    print("Column_count",df.shape[1])
    print("Datatypes:")
    print(df.dtypes)
    print(".........................................")


Table: billing
Row_count 115313
Column_count 9
Datatypes:
invoice_id               object
customer_id              object
billing_date             object
billing_period_month     object
base_amount_inr         float64
gst_amount_inr          float64
total_amount_inr        float64
due_date                 object
payment_status           object
dtype: object
.........................................
Table: cities
Row_count 68
Column_count 8
Datatypes:
city_id       object
city_name     object
state_id      object
state_name    object
zone          object
region_id     object
tier          object
pin_prefix     int64
dtype: object
.........................................
Table: complaints
Row_count 16584
Column_count 7
Datatypes:
complaint_id       object
customer_id        object
complaint_date     object
complaint_type     object
severity           object
status             object
resolution_date    object
dtype: object
.........................................
Table: contracts
Row_co

In [11]:
Profile_records = []

for table_name,df in all_dfs.items():
    Profile_records.append({"table_name":table_name,"row_count":df.shape[0],"column_count":df.shape[1]})
Profile_summary = pd.DataFrame(Profile_records)
Profile_summary


,table_name,row_count,column_count
0,billing,115313,9
1,cities,68,8
2,complaints,16584,7
3,contracts,10607,9
4,customer_feedback,28499,7
5,customers,19076,25
6,data_quality_issue_log,20,3
7,devices,19000,8
8,employees,800,9
9,marketing_campaigns,40,9


In [12]:
#Missing values

all_dfs["customers"].isna().sum()
missing_percentage = ((all_dfs["customers"].isna().sum() / len(all_dfs["customers"]))*100).round(2)

missing_percentage

# missing report values

customers_missing_report = pd.DataFrame({"missing_count": all_dfs["customers"].isna().sum(),
                                         "missing_percentage":missing_percentage})
customers_missing_report

# showing only columns having null values

customers_null_columns = customers_missing_report[customers_missing_report["missing_count"]>0]
customers_null_columns

#make the column real column resetting index

customers_null_columns = customers_null_columns.reset_index()
customers_null_columns = customers_null_columns.rename(columns = {"index":"column_name"})
customers_null_columns



,column_name,missing_count,missing_percentage
0,email,745,3.91
1,address,380,1.99
2,annual_income_inr,954,5.00
3,churn_date,15560,81.57


In [13]:
# Running loop in all 24 tablw to check missing values

for table_name, df in all_dfs.items():
    missing_count = df.isna().sum()
    column_with_null = missing_count[missing_count>0]

    print(f"Table: {table_name}")
    print(column_with_null)
    print("-------------------------------------")
    

Table: billing
Series([], dtype: int64)
-------------------------------------
Table: cities
Series([], dtype: int64)
-------------------------------------
Table: complaints
resolution_date    7348
dtype: int64
-------------------------------------
Table: contracts
Series([], dtype: int64)
-------------------------------------
Table: customer_feedback
Series([], dtype: int64)
-------------------------------------
Table: customers
email                  745
address                380
annual_income_inr      954
churn_date           15560
dtype: int64
-------------------------------------
Table: data_quality_issue_log
Series([], dtype: int64)
-------------------------------------
Table: devices
Series([], dtype: int64)
-------------------------------------
Table: employees
Series([], dtype: int64)
-------------------------------------
Table: marketing_campaigns
Series([], dtype: int64)
-------------------------------------
Table: network_quality
Series([], dtype: int64)
-------------------

In [14]:
for table_name, df in all_dfs.items():
    missing_count = df.isna().sum()

    missing_percentage = (missing_count/len(df)*100).round(2)

    missing_report = pd.DataFrame({"missing_count":missing_count,"missing_percentage":missing_percentage})
    missing_report = missing_report[missing_report["missing_count"]>0]
    if not missing_report.empty:
         print(f"Table: {table_name}")
         print(missing_report)
         print("*-------------------------------*----------------------------------*")


        
       
        
        

    

Table: complaints
                 missing_count  missing_percentage
resolution_date           7348               44.31
*-------------------------------*----------------------------------*
Table: customers
                   missing_count  missing_percentage
email                        745                3.91
address                      380                1.99
annual_income_inr            954                5.00
churn_date                 15560               81.57
*-------------------------------*----------------------------------*
Table: subscriptions
          missing_count  missing_percentage
plan_id              41                0.20
end_date          17017               82.92
*-------------------------------*----------------------------------*
Table: support_tickets
                  missing_count  missing_percentage
resolution_hours          13366               42.45
resolution_date           13366               42.45
*-------------------------------*--------------------------

In [15]:
# creating missing values report


all_missing_reports = []

for table_name, df in all_dfs.items():
    missing_count = df.isna().sum()

    missing_percentage = (missing_count / len(df) * 100).round(2)

    missing_report = pd.DataFrame({"missing_count": missing_count,"missing_percentage": missing_percentage})

    missing_report = missing_report[missing_report["missing_count"] > 0].reset_index()

    missing_report = missing_report.rename(columns={"index": "column_name"})

    if not missing_report.empty:
        missing_report["table_name"] = table_name

        missing_report = missing_report[
            ["table_name","column_name","missing_count","missing_percentage"]]

        all_missing_reports.append(missing_report)

len(all_missing_reports)

4

In [16]:
Missing_values_summary = pd.concat(
    all_missing_reports,
    ignore_index=True
)

Missing_values_summary

,table_name,column_name,missing_count,missing_percentage
0,complaints,resolution_date,7348,44.31
1,customers,email,745,3.91
2,customers,address,380,1.99
3,customers,annual_income_inr,954,5.00
4,customers,churn_date,15560,81.57
5,subscriptions,plan_id,41,0.20
6,subscriptions,end_date,17017,82.92
7,support_tickets,resolution_hours,13366,42.45
8,support_tickets,resolution_date,13366,42.45


In [17]:
# Check for duplicate rows — especially duplicate customer_id in customers.csv and duplicate invoice_id in billing.csv.

# count exact duplicate customer rows

duplicate_customer_rows = all_dfs["customers"].duplicated().sum()



# duplicate customer_id

duplicate_customer_id = all_dfs["customers"].duplicated( 
    subset = ["customer_id"]).sum()



print(duplicate_customer_rows,
      duplicate_customer_id)




76 76


In [18]:
# checking billing duplicate rows and billing_invoice_id duplicate

duplicate_billing_rows = all_dfs["billing"].duplicated().sum()

# checking duplicate invoice_id

duplicate_billing_invoice_id = all_dfs["billing"].duplicated(
    subset = ["invoice_id"]).sum()

print(duplicate_billing_rows)
print(duplicate_billing_invoice_id)

344
344


In [19]:
# duplicate customer records

duplicate_customer_record = all_dfs["customers"][all_dfs["customers"].duplicated(
    subset = ["customer_id"], keep = False)].sort_values("customer_id")
duplicate_customer_record.head(10)

,customer_id,first_name,last_name,gender,date_of_birth,age,email,phone_number,address,city_id,...,occupation,annual_income_inr,customer_segment,product_line,plan_id,acquisition_channel,acquisition_date,tenure_months,customer_status,churn_date
97,C0000098,Ayaan,Sheikh,Male,31-03-1977,49,ayaan.sheikh13@rediffmail.com,917063719000,"House No. 229, Old Phase, Siliguri",CT0052,...,School Teacher,538733.0,Premium,5G,PL013,Retail Store,04-02-2021,61,Active,NaN
19044,C0000098,Ayaan,Sheikh,Male,31-03-1977,49,ayaan.sheikh13@rediffmail.com,917063719000,"House No. 229, Old Phase, Siliguri",CT0052,...,School Teacher,538733.0,Premium,5G,PL013,Retail Store,04-02-2021,61,Active,NaN
19074,C0000169,Yash,Shinde,Male,01-04-1971,55,yash.shinde18@outlook.com,918905657883,"Flat 66, Lake Nagar, Belagavi",CT0041,...,Sales Executive,506678.0,Value,Prepaid Mobile,PL003,Retail Store,08-11-2020,64,Active,NaN
168,C0000169,Yash,Shinde,Male,01-04-1971,55,yash.shinde18@outlook.com,918905657883,"Flat 66, Lake Nagar, Belagavi",CT0041,...,Sales Executive,506678.0,Value,Prepaid Mobile,PL003,Retail Store,08-11-2020,64,Active,NaN
19025,C0000784,Sita,Hussain,Female,31-03-2008,18,sita.hussain386@rediffmail.com,917836729786,"Apartment 26, Garden Colony, Shimla",CT0061,...,Self Employed,626862.0,Mass,Prepaid Mobile,PL002,Retail Store,27-09-2018,90,Active,NaN
783,C0000784,Sita,Hussain,Female,31-03-2008,18,sita.hussain386@rediffmail.com,917836729786,"Apartment 26, Garden Colony, Shimla",CT0061,...,Self Employed,626862.0,Mass,Prepaid Mobile,PL002,Retail Store,27-09-2018,90,Active,NaN
1391,C0001392,Rohan,Pradhan,Male,31-03-1980,46,rohan.pradhan706@rediffmail.com,919082312668,"Apartment 19, Lake Phase, Kolkata",CT0005,...,Auto/Cab Driver,457301.0,Premium,5G,PL013,Online,20-08-2024,19,Active,NaN
19051,C0001392,Rohan,Pradhan,Male,31-03-1980,46,rohan.pradhan706@rediffmail.com,919082312668,"Apartment 19, Lake Phase, Kolkata",CT0005,...,Auto/Cab Driver,457301.0,Premium,5G,PL013,Online,20-08-2024,19,Active,NaN
1393,C0001394,Preeti,Pawar,Female,31-03-2008,18,preeti.pawar464@yahoo.in,919078014489,"Apartment 300, Tilak Road, Ludhiana",CT0031,...,Doctor,1263796.0,Value,Postpaid Mobile,PL007,Online,17-02-2022,49,Active,NaN
19020,C0001394,Preeti,Pawar,Female,31-03-2008,18,preeti.pawar464@yahoo.in,919078014489,"Apartment 300, Tilak Road, Ludhiana",CT0031,...,Doctor,1263796.0,Value,Postpaid Mobile,PL007,Online,17-02-2022,49,Active,NaN


In [20]:
# checking duplicate mask in billing

duplicate_billing_records = all_dfs["billing"][all_dfs["billing"].duplicated(
    subset = ["invoice_id"],keep = False)].sort_values("invoice_id")
duplicate_billing_records.head(10)

,invoice_id,customer_id,billing_date,billing_period_month,base_amount_inr,gst_amount_inr,total_amount_inr,due_date,payment_status
127,INV00000128,C0000030,02-10-2025,10-2025,562.30,101.21,663.51,17-10-2025,Paid
115181,INV00000128,C0000030,02-10-2025,10-2025,562.30,101.21,663.51,17-10-2025,Paid
115278,INV00000652,C0000112,04-07-2025,07-2025,552.95,99.53,652.48,19-07-2025,Overdue
651,INV00000652,C0000112,04-07-2025,07-2025,552.95,99.53,652.48,19-07-2025,Overdue
1219,INV00001220,C0000232,30-01-2026,01-2026,584.68,105.24,689.92,14-02-2026,Overdue
115013,INV00001220,C0000232,30-01-2026,01-2026,584.68,105.24,689.92,14-02-2026,Overdue
1522,INV00001523,C0000272,04-07-2025,07-2025,747.90,134.62,882.52,19-07-2025,Paid
115081,INV00001523,C0000272,04-07-2025,07-2025,747.90,134.62,882.52,19-07-2025,Paid
1599,INV00001600,C0000282,30-01-2026,01-2026,486.59,87.59,574.18,14-02-2026,Overdue
115275,INV00001600,C0000282,30-01-2026,01-2026,486.59,87.59,574.18,14-02-2026,Overdue


In [21]:
# calculating percentage of duplicates in customer & billing

percentage_duplicate_customer_rows = round(duplicate_customer_rows/len(all_dfs["customers"])*100,2)

percentage_duplicate_billing_rows = round(duplicate_billing_rows/len(all_dfs["billing"])*100,2)

print("Customer_duplicate_percentage:",percentage_duplicate_customer_rows)
print("Billing_duplicate_percentage:",percentage_duplicate_billing_rows)

Customer_duplicate_percentage: 0.4
Billing_duplicate_percentage: 0.3


In [22]:
# final duplicate summary

Duplicate_summary = pd.DataFrame({"table_name":["customers","billing"],
                                  "key_column":["customer_id","invoice_id"],
                                  "exact_duplicate_rows":[duplicate_customer_rows,duplicate_billing_rows],
                                  "duplicate_key_rows":[duplicate_customer_id,duplicate_billing_invoice_id],
                                  "duplicate_percentage":[percentage_duplicate_customer_rows,percentage_duplicate_billing_rows]})

Duplicate_summary

,table_name,key_column,exact_duplicate_rows,duplicate_key_rows,duplicate_percentage
0,customers,customer_id,76,76,0.4
1,billing,invoice_id,344,344,0.3


In [23]:
# check exact duplicate rows in all 24 table

for table_name,df in all_dfs.items():
    duplicate_count = df.duplicated().sum()
    if duplicate_count>0:
        print("Table:",table_name)
        print("Exact_duplicate_rows:",duplicate_count)
        print("---------------------------------------------------")

Table: billing
Exact_duplicate_rows: 344
---------------------------------------------------
Table: customers
Exact_duplicate_rows: 76
---------------------------------------------------
Table: payments
Exact_duplicate_rows: 276
---------------------------------------------------


In [24]:
# checking duplicate in payments table

all_dfs["payments"].columns.tolist()

['payment_id',
 'invoice_id',
 'customer_id',
 'payment_date',
 'amount_inr',
 'payment_method',
 'payment_status']

In [25]:
# checking payment duplicate

duplicate_payment_rows = all_dfs["payments"].duplicated().sum()
duplicate_payment_id = all_dfs["payments"].duplicated( subset = ["payment_id"]).sum()

print("Exact_duplicate_payment_rows:",duplicate_payment_rows)
print("Duplicate_payment_id_rows:",duplicate_payment_id)

Exact_duplicate_payment_rows: 276
Duplicate_payment_id_rows: 276


In [26]:
# duplicate payment record

duplicate_payment_record = all_dfs["payments"][all_dfs["payments"].duplicated( subset = ["payment_id"],keep=False)].sort_values("payment_id")
duplicate_payment_record

,payment_id,invoice_id,customer_id,payment_date,amount_inr,payment_method,payment_status
142,PAY00000143,INV00000182,C0000038,05-04-2026,922.76,UPI,Success
92320,PAY00000143,INV00000182,C0000038,05-04-2026,922.76,UPI,Success
151,PAY00000152,INV00000192,C0000038,09-06-2025,794.09,Credit Card,Success
92291,PAY00000152,INV00000192,C0000038,09-06-2025,794.09,Credit Card,Success
165,PAY00000166,INV00000212,C0000042,14-10-2025,1120.42,Credit Card,Success
...,...,...,...,...,...,...,...
92223,PAY00091274,INV00113937,C0018822,13-11-2025,685.67,UPI,Success
92236,PAY00091866,INV00114693,C0018957,24-10-2025,867.94,Debit Card,Success
91865,PAY00091866,INV00114693,C0018957,24-10-2025,867.94,Debit Card,Success
92297,PAY00091956,INV00114804,C0018978,18-04-2025,903.99,RTGS,Success


In [27]:
# payment duplicate percentage

percentage_payment_duplicate_rows = round(duplicate_payment_rows/len(all_dfs["payments"])*100,2)
print("Payment_duplicate_percentage:",percentage_payment_duplicate_rows,"%")

Payment_duplicate_percentage: 0.3 %


In [28]:
# final duplicate summary

Duplicate_summary = pd.DataFrame({"table_name":["customers","billing","payments"],
                                  "key_column":["customer_id","invoice_id","payment_id"],
                                  "exact_duplicate_rows":[duplicate_customer_rows,duplicate_billing_rows,duplicate_payment_rows],
                                  "duplicate_key_rows":[duplicate_customer_id,duplicate_billing_invoice_id,duplicate_payment_id],
                                  "duplicate_percentage":[percentage_duplicate_customer_rows,percentage_duplicate_billing_rows,percentage_payment_duplicate_rows]})
Duplicate_summary

,table_name,key_column,exact_duplicate_rows,duplicate_key_rows,duplicate_percentage
0,customers,customer_id,76,76,0.4
1,billing,invoice_id,344,344,0.3
2,payments,payment_id,276,276,0.3


In [29]:
# •	Validate data types — dates should parse as dates (note the DD-MM-YYYY format), amounts should be numeric.

# checking data type

print("current_date:",all_dfs["customers"]["date_of_birth"].dtype)

all_dfs["customers"][["date_of_birth"]].head()

current_date: object


,date_of_birth
0,31-03-1988
1,31-03-1974
2,31-03-1978
3,31-03-1988
4,31-03-1988


In [30]:
# date conversion test 
parsed_date_of_birth = pd.to_datetime(
     all_dfs["customers"]["date_of_birth"],
     format="%d-%m-%y",errors="coerce"
)
print("parsed_data_type:",parsed_date_of_birth.dtype)
parsed_date_of_birth.head(10)

parsed_data_type: datetime64[ns]


0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
5   NaT
6   NaT
7   NaT
8   NaT
9   NaT
Name: date_of_birth, dtype: datetime64[ns]

In [31]:
# change format here
parsed_date_of_birth = pd.to_datetime(
     all_dfs["customers"]["date_of_birth"],
     format="%d-%m-%Y",errors="coerce"
)
print("parsed_data_type:",parsed_date_of_birth.dtype)
parsed_date_of_birth.head(10)


parsed_data_type: datetime64[ns]


0   1988-03-31
1   1974-03-31
2   1978-03-31
3   1988-03-31
4   1988-03-31
5   1990-03-31
6   2000-03-31
7   1991-04-01
8   1996-03-31
9   2006-03-31
Name: date_of_birth, dtype: datetime64[ns]

In [32]:
# invalid date of birth

invalid_date_of_birth_mask = (all_dfs["customers"]["date_of_birth"].notna() 
                              & parsed_date_of_birth.isna())

invalid_date_birth_count = invalid_date_of_birth_mask.sum()

print("Invalid_date_of_birth_values:",invalid_date_birth_count)

Invalid_date_of_birth_values: 0


In [33]:
# find all date column in 24 tables

date_columns = []

for table_name,df in all_dfs.items():
    for column_name in df.columns:
        if "date" in column_name.lower():
            date_columns.append((table_name,column_name))

date_columns

[('billing', 'billing_date'),
 ('billing', 'due_date'),
 ('complaints', 'complaint_date'),
 ('complaints', 'resolution_date'),
 ('contracts', 'start_date'),
 ('contracts', 'end_date'),
 ('customer_feedback', 'feedback_date'),
 ('customers', 'date_of_birth'),
 ('customers', 'acquisition_date'),
 ('customers', 'churn_date'),
 ('devices', 'purchase_date'),
 ('employees', 'hire_date'),
 ('marketing_campaigns', 'start_date'),
 ('marketing_campaigns', 'end_date'),
 ('payments', 'payment_date'),
 ('plan_history', 'change_date'),
 ('recharges', 'recharge_date'),
 ('retention_campaigns', 'contact_date'),
 ('stores', 'opened_date'),
 ('subscriptions', 'start_date'),
 ('subscriptions', 'end_date'),
 ('support_tickets', 'created_date'),
 ('support_tickets', 'resolution_date')]

In [34]:
table_name,column_name = date_columns[0]

print("Table:",table_name)
print("Date column:",column_name)

Table: billing
Date column: billing_date


In [35]:
# check date in billing table

parsed_date = pd.to_datetime(all_dfs[table_name][column_name],format="%d-%m-%Y",errors="coerce")

print("parsed data type:",parsed_date.dtype)
parsed_date.head()

parsed data type: datetime64[ns]


0   2026-03-31
1   2026-03-01
2   2026-01-30
3   2025-12-31
4   2025-12-01
Name: billing_date, dtype: datetime64[ns]

In [36]:
invalid_date_mask = (
    all_dfs[table_name][column_name].notna()
    & parsed_date.isna()
)

invalid_date_count = invalid_date_mask.sum()

print("Invalid billing_date values:", invalid_date_count)

Invalid billing_date values: 0


In [37]:
# creating a list for data validation

date_validation_results = []

for table_name, column_name in date_columns:

    original_date = all_dfs[table_name][column_name]

    parsed_date = pd.to_datetime(
        original_date,
        format="%d-%m-%Y",errors="coerce")

    invalid_date_count = (
        original_date.notna() & parsed_date.isna()).sum()

    date_validation_results.append({
        "table_name": table_name,
        "column_name": column_name,
        "invalid_date_count": invalid_date_count})

len(date_validation_results)

23

In [38]:
Date_validation_summary = pd.DataFrame(date_validation_results)

Date_validation_summary

,table_name,column_name,invalid_date_count
0,billing,billing_date,0
1,billing,due_date,0
2,complaints,complaint_date,0
3,complaints,resolution_date,0
4,contracts,start_date,0
5,contracts,end_date,0
6,customer_feedback,feedback_date,0
7,customers,date_of_birth,0
8,customers,acquisition_date,383
9,customers,churn_date,0


In [39]:
Invalid_date_summary = Date_validation_summary[
    Date_validation_summary["invalid_date_count"] > 0
].reset_index(drop=True)

Invalid_date_summary

,table_name,column_name,invalid_date_count
0,customers,acquisition_date,383


In [40]:
parsed_acquisition_date = pd.to_datetime(
    all_dfs["customers"]["acquisition_date"],
    format="%d-%m-%Y",
    errors="coerce")

invalid_acquisition_mask = (
    all_dfs["customers"]["acquisition_date"].notna()
    & parsed_acquisition_date.isna())

invalid_acquisition_examples = all_dfs["customers"].loc[
    invalid_acquisition_mask,
    ["customer_id", "acquisition_date"]]

invalid_acquisition_examples.head(10)

,customer_id,acquisition_date
3,C0000004,2014/10/18
33,C0000034,2023/04/16
59,C0000060,2021/06/13
74,C0000075,2024/12/13
88,C0000089,2021/10/31
94,C0000095,2018/06/01
151,C0000152,2019/07/28
308,C0000309,2016/09/03
340,C0000341,2014/05/30
347,C0000348,2014/01/01


In [41]:
alternate_parsed_dates = pd.to_datetime(
    invalid_acquisition_examples["acquisition_date"],
    format="%Y/%m/%d",
    errors="coerce")

print("Converted using YYYY/MM/DD:", alternate_parsed_dates.notna().sum())
print("Still invalid:", alternate_parsed_dates.isna().sum())

Converted using YYYY/MM/DD: 383
Still invalid: 0


In [42]:
# validating monetary columns


amount_columns = []

for table_name, df in all_dfs.items():
    for column_name in df.columns:
        if column_name.lower().endswith("_inr"):
            amount_columns.append((table_name, column_name))

amount_columns

[('billing', 'base_amount_inr'),
 ('billing', 'gst_amount_inr'),
 ('billing', 'total_amount_inr'),
 ('customers', 'annual_income_inr'),
 ('devices', 'device_price_inr'),
 ('marketing_campaigns', 'budget_inr'),
 ('payments', 'amount_inr'),
 ('recharges', 'amount_inr'),
 ('subscriptions', 'monthly_charge_inr')]

In [43]:
# current data type

for table_name, column_name in amount_columns:

    current_dtype = all_dfs[table_name][column_name].dtype

    print(table_name, "|", column_name, "|", current_dtype)

billing | base_amount_inr | float64
billing | gst_amount_inr | float64
billing | total_amount_inr | float64
customers | annual_income_inr | float64
devices | device_price_inr | int64
marketing_campaigns | budget_inr | int64
payments | amount_inr | float64
recharges | amount_inr | float64
subscriptions | monthly_charge_inr | float64


In [44]:
# create a formal summary table

amount_validation_results = []

for table_name, column_name in amount_columns:

    amount_series = all_dfs[table_name][column_name]

    is_numeric = pd.api.types.is_numeric_dtype(amount_series)

    amount_validation_results.append({
        "table_name": table_name,"column_name": column_name,
        "current_dtype": str(amount_series.dtype),"is_numeric": is_numeric})

Amount_validation_summary = pd.DataFrame(amount_validation_results)

Amount_validation_summary

,table_name,column_name,current_dtype,is_numeric
0,billing,base_amount_inr,float64,True
1,billing,gst_amount_inr,float64,True
2,billing,total_amount_inr,float64,True
3,customers,annual_income_inr,float64,True
4,devices,device_price_inr,int64,True
5,marketing_campaigns,budget_inr,int64,True
6,payments,amount_inr,float64,True
7,recharges,amount_inr,float64,True
8,subscriptions,monthly_charge_inr,float64,True


In [45]:
#•	Check for outliers in data_gb_used and negative values in total_amount_inr. Flag them.

# finding outliers using IQR Method

# first locate the column

target_column = ["data_gb_used","total_amount_inr"]
for table_name,df in all_dfs.items():
    for column_name in target_column:
        if column_name in df.columns:
            print(column_name,"found in table:",table_name)



total_amount_inr found in table: billing
data_gb_used found in table: usage_data


In [46]:
# calculating IQR for usage_data

data_usage = all_dfs["usage_data"]["data_gb_used"]

Q1 = data_usage.quantile(0.25)
Q3 = data_usage.quantile(0.75)

IQR = Q3-Q1

print("Q1:",Q1)
print("Q3:",Q3)
print("IQR:",IQR)

Q1: 11.39
Q3: 32.63
IQR: 21.240000000000002


In [47]:
# calculating lower_bound & upper_bound

lower_bound = Q1-(1.5*IQR)
upper_bound = Q3+(1.5*IQR)

print("lower_bound:",round(lower_bound,2))
print("upper_bound:",round(upper_bound,2))

lower_bound: -20.47
upper_bound: 64.49


In [48]:
# flag data_usage

data_gb_outlier_flag = ((data_usage<lower_bound) | (data_usage>upper_bound))

all_dfs["usage_data"]["data_gb_outlier_flag"] = data_gb_outlier_flag
all_dfs["usage_data"]["data_gb_outlier_flag"].value_counts()

data_gb_outlier_flag
False    52520
True      4480
Name: count, dtype: int64

In [49]:
# flag outlier in billing,so we have to check the negative values so we will be using 
#explicit business rules here

negative_amount_flag = (all_dfs["billing"]["total_amount_inr"]<0)

all_dfs["billing"]["negative_amount_flag"] = negative_amount_flag
all_dfs["billing"]["negative_amount_flag"].value_counts()

negative_amount_flag
False    115084
True        229
Name: count, dtype: int64

In [50]:
# final summary for both check

usage_outlier_count = data_gb_outlier_flag.sum()
usage_outlier_percentage = round(
    usage_outlier_count / len(all_dfs["usage_data"]) * 100,2)

negative_amount_count = negative_amount_flag.sum()
negative_amount_percentage = round(
    negative_amount_count / len(all_dfs["billing"]) * 100,2)

Outlier_summary = pd.DataFrame({
    "table_name": ["usage_data", "billing"],
    "column_name": ["data_gb_used", "total_amount_inr"],
    "check_rule": ["Outside IQR limits","Value less than 0"],
    "flagged_count": [usage_outlier_count,negative_amount_count],
    "flagged_percentage": [usage_outlier_percentage,negative_amount_percentage]})

Outlier_summary

,table_name,column_name,check_rule,flagged_count,flagged_percentage
0,usage_data,data_gb_used,Outside IQR limits,4480,7.86
1,billing,total_amount_inr,Value less than 0,229,0.20


In [51]:
#•	Verify referential integrity — do all customer_id values in subscriptions, billing and usage exist in customers.csv?

# check in subscription first

subscriptions_customer_exists = (
    all_dfs["subscriptions"]["customer_id"].isin(
        all_dfs["customers"]["customer_id"]))

subscriptions_customer_exists.value_counts()

customer_id
True    20523
Name: count, dtype: int64

In [52]:
# in billing 

billing_customer_exists = (
    all_dfs["billing"]["customer_id"].isin(
        all_dfs["customers"]["customer_id"]))

billing_customer_exists.value_counts()

customer_id
True    115313
Name: count, dtype: int64

In [53]:
usage_data_customer_exists = (all_dfs["usage_data"]["customer_id"].isin(
    all_dfs["customers"]["customer_id"]))
usage_data_customer_exists.value_counts()

customer_id
True    57000
Name: count, dtype: int64

In [54]:
# final summary

Referential_integrity_summary = pd.DataFrame({
    "table_name": ["subscriptions","billing","usage_data"],

    "total_rows": [len(all_dfs["subscriptions"]),len(all_dfs["billing"]),len(all_dfs["usage_data"])],

    "matched_customer_ids": [subscriptions_customer_exists.sum(),billing_customer_exists.sum(),
                             usage_data_customer_exists.sum()],

    "orphan_customer_ids": [(~subscriptions_customer_exists).sum(),(~billing_customer_exists).sum(),
                            (~usage_data_customer_exists).sum()],

    "match_percentage": [
        round(subscriptions_customer_exists.mean() * 100, 2),
        round(billing_customer_exists.mean() * 100, 2),
        round(usage_data_customer_exists.mean() * 100, 2)]})

Referential_integrity_summary

,table_name,total_rows,matched_customer_ids,orphan_customer_ids,match_percentage
0,subscriptions,20523,20523,0,100.0
1,billing,115313,115313,0,100.0
2,usage_data,57000,57000,0,100.0


In [55]:
#•	Compare your findings against data_quality_issue_log.csv, then write a 1-page Data Quality Report.


all_dfs["data_quality_issue_log"].head(10)

,table,issue_type,rows_affected
0,customers,missing_email,760
1,customers,missing_address,380
2,customers,missing_income,950
3,customers,invalid_phone,228
4,customers,invalid_email,285
5,customers,incorrect_pin,190
6,customers,misspelled_city,380
7,customers,inconsistent_capitalisation,570
8,customers,impossible_age,38
9,customers,mixed_date_format,380


In [56]:
all_dfs["data_quality_issue_log"].shape

(20, 3)

In [57]:
all_dfs["data_quality_issue_log"]

,table,issue_type,rows_affected
0,customers,missing_email,760
1,customers,missing_address,380
2,customers,missing_income,950
3,customers,invalid_phone,228
4,customers,invalid_email,285
5,customers,incorrect_pin,190
6,customers,misspelled_city,380
7,customers,inconsistent_capitalisation,570
8,customers,impossible_age,38
9,customers,mixed_date_format,380


In [58]:
#Creating a separate comparison DataFrame

data_quality_comparison = all_dfs["data_quality_issue_log"].copy()

#Rename rows_affected so it clearly represents the issue-log count
data_quality_comparison = data_quality_comparison.rename(
    columns={"rows_affected": "expected_rows_affected"}
)

#Add an empty column for your calculated results

data_quality_comparison["actual_rows_affected"] = pd.NA

In [59]:
# missing emails

missing_email_actual = (
    all_dfs["customers"]["email"].fillna("").str.strip().eq("").sum())

missing_email_actual

np.int64(745)

In [60]:
#actual count in the missing_email row

data_quality_comparison.loc[
    data_quality_comparison["issue_type"] == "missing_email",
    "actual_rows_affected"] = missing_email_actual

data_quality_comparison.head(1)



,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745


In [61]:
#actual missing-address count

missing_address_actual = (
    all_dfs["customers"]["address"].fillna("").str.strip().eq("").sum())

missing_address_actual

np.int64(380)

In [62]:
#Record the missing-address result

data_quality_comparison.loc[
    data_quality_comparison["issue_type"] == "missing_address",
    "actual_rows_affected"] = missing_address_actual

data_quality_comparison.head(2)

,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380


In [63]:
#actual missing-income count

missing_income_actual = (
    all_dfs["customers"]["annual_income_inr"].isna().sum())

missing_income_actual

np.int64(954)

In [64]:
#Record the missing-income result

data_quality_comparison.loc[
    data_quality_comparison["issue_type"] == "missing_income",
    "actual_rows_affected"
] = missing_income_actual

data_quality_comparison.head(3)

,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954


In [65]:
#Actual missing phone numbers

phone_text = (
    all_dfs["customers"]["phone_number"].fillna("").astype(str).str.strip())

invalid_phone_actual = (~phone_text.str.fullmatch(r"91\d{10}")).sum()

invalid_phone_actual

np.int64(228)

In [66]:
#Record the invalid-phone result

data_quality_comparison.loc[
    data_quality_comparison["issue_type"] == "invalid_phone",
    "actual_rows_affected"] = invalid_phone_actual

data_quality_comparison.head(4)

,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228


In [67]:
#invalid non-empty emails


email_text = (
    all_dfs["customers"]["email"]
    .fillna("").str.strip())

invalid_email_actual = (email_text.ne("")& ~email_text.str.fullmatch(
        r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")).sum()

invalid_email_actual

np.int64(286)

In [68]:
#Record the invalid-email result

data_quality_comparison.loc[
    data_quality_comparison["issue_type"] == "invalid_email",
    "actual_rows_affected"] = invalid_email_actual

data_quality_comparison.head(5)

,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286


In [69]:
#actual invalid-PIN count

pin_text = (
    all_dfs["customers"]["pin_code"].fillna("").astype(str).str.strip())

invalid_pin_actual = (~pin_text.str.fullmatch(r"\d{6}")).sum()

invalid_pin_actual

np.int64(191)

In [70]:
#Record the invalid-pin count


data_quality_comparison.loc[
    data_quality_comparison["issue_type"] == "incorrect_pin",
    "actual_rows_affected"] = invalid_pin_actual

data_quality_comparison.head(6)

,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286
5,customers,incorrect_pin,190,191


In [71]:
# inspecting misspelled_city

all_dfs["customers"].filter(like="city").head()

,city_id,city_name,city_tier
0,CT0026,Raipur,Tier-2
1,CT0009,Gurugram,Metro
2,CT0020,Vadodara,Tier-2
3,CT0015,Nagpur,Tier-2
4,CT0043,Warangal,Tier-3


In [72]:
# verify official city

all_dfs["cities"][["city_id", "city_name"]].head()

,city_id,city_name
0,CT0001,New Delhi
1,CT0002,Mumbai
2,CT0003,Bengaluru
3,CT0004,Chennai
4,CT0005,Kolkata


In [73]:
# comparing

city_check = all_dfs["customers"][
    ["customer_id", "city_id", "city_name"]].merge(all_dfs["cities"][["city_id", "city_name"]],
    on="city_id",how="left",suffixes=("_customer", "_official"))

city_check.head()

,customer_id,city_id,city_name_customer,city_name_official
0,C0000001,CT0026,Raipur,Raipur
1,C0000002,CT0009,Gurugram,Gurugram
2,C0000003,CT0020,Vadodara,Vadodara
3,C0000004,CT0015,Nagpur,Nagpur
4,C0000005,CT0043,Warangal,Warangal


In [74]:
#Calculate misspelled city names:


customer_city_normalized = (
    city_check["city_name_customer"].fillna("").str.strip().str.casefold())

official_city_normalized = (city_check["city_name_official"].fillna("").str.strip().str.casefold())

misspelled_city_actual = (customer_city_normalized != official_city_normalized).sum()

misspelled_city_actual

np.int64(380)

In [75]:
#Record the misspelled-city result:

data_quality_comparison.loc[data_quality_comparison["issue_type"] == "misspelled_city",
    "actual_rows_affected"] = misspelled_city_actual

data_quality_comparison.head(7)

,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286
5,customers,incorrect_pin,190,191
6,customers,misspelled_city,380,380


In [76]:
#Calculate capitalization inconsistencies


customer_city_clean = (
    city_check["city_name_customer"].fillna("").str.strip())

official_city_clean = (
    city_check["city_name_official"].fillna("").str.strip())

capitalisation_mask = (
    customer_city_clean.str.casefold()
    == official_city_clean.str.casefold()) & (customer_city_clean != official_city_clean)

inconsistent_capitalisation_actual = capitalisation_mask.sum()

inconsistent_capitalisation_actual

np.int64(561)

In [77]:
#Recalculate using proper-title-case validation:



capitalisation_mask = (
    customer_city_clean.ne("")
    & ~customer_city_clean.str.istitle())

inconsistent_capitalisation_actual = capitalisation_mask.sum()

inconsistent_capitalisation_actual

np.int64(571)

In [78]:
#Record the capitalization result


data_quality_comparison.loc[
    data_quality_comparison["issue_type"] == "inconsistent_capitalisation",
    "actual_rows_affected"
] = inconsistent_capitalisation_actual

data_quality_comparison.head(8)

,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286
5,customers,incorrect_pin,190,191
6,customers,misspelled_city,380,380
7,customers,inconsistent_capitalisation,570,571


In [79]:
#Calculate impossible ages


customer_age = all_dfs["customers"]["age"]

impossible_age_actual = ((customer_age < 0)| (customer_age > 120)).sum()

impossible_age_actual

np.int64(23)

In [80]:
#Check the age groups separately


print("Age below 0:", (customer_age < 0).sum())
print("Age above 100:", (customer_age > 100).sum())
print("Age above 120:", (customer_age > 120).sum())



Age below 0: 6
Age above 100: 17
Age above 120: 17


In [81]:
#Check the adult-customer rule


print("Age below 18:", (customer_age < 18).sum())

adult_age_rule_count = ((customer_age < 18)| (customer_age > 120)).sum()

print("Outside age range 18–120:", adult_age_rule_count)

Age below 18: 21
Outside age range 18–120: 38


In [82]:
#Save and record the corrected age result



impossible_age_actual = adult_age_rule_count

data_quality_comparison.loc[
    data_quality_comparison["issue_type"] == "impossible_age",
    "actual_rows_affected"] = impossible_age_actual

data_quality_comparison.head(9)

,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286
5,customers,incorrect_pin,190,191
6,customers,misspelled_city,380,380
7,customers,inconsistent_capitalisation,570,571
8,customers,impossible_age,38,38


In [83]:
#Calculate the mixed acquisition-date formats

acquisition_text = (
    all_dfs["customers"]["acquisition_date"].astype("string").str.strip())

standard_acquisition = pd.to_datetime(acquisition_text,format="%d-%m-%Y",errors="coerce")

alternate_acquisition = pd.to_datetime(acquisition_text,format="%Y/%m/%d",errors="coerce")

mixed_date_format_actual = (standard_acquisition.isna()& alternate_acquisition.notna()).sum()

mixed_date_format_actual

np.int64(383)

In [84]:
#recording the mixed acquisition date formats


data_quality_comparison.loc[
data_quality_comparison["issue_type"] == "mixed_date_format",
"actual_rows_affected"]=mixed_date_format_actual

data_quality_comparison.head(10)


,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286
5,customers,incorrect_pin,190,191
6,customers,misspelled_city,380,380
7,customers,inconsistent_capitalisation,570,571
8,customers,impossible_age,38,38
9,customers,mixed_date_format,380,383


In [85]:
# recording the duplicate customers

data_quality_comparison.loc[
data_quality_comparison["issue_type"]== "duplicate_customers",
"actual_rows_affected"] = duplicate_customer_rows

data_quality_comparison[data_quality_comparison["issue_type"] == "duplicate_customers"]

data_quality_comparison.head(11)

,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286
5,customers,incorrect_pin,190,191
6,customers,misspelled_city,380,380
7,customers,inconsistent_capitalisation,570,571
8,customers,impossible_age,38,38
9,customers,mixed_date_format,380,383


In [86]:
#checking GST Amount

expected_gst = (all_dfs["billing"]["base_amount_inr"]*0.18).round(2)

expected_gst.head()

0    268.34
1    251.33
2    256.90
3    275.06
4    270.47
Name: base_amount_inr, dtype: float64

In [87]:
# COMPARING IT WITH STORED GST IN BILLING

incorrect_gst_mask = (all_dfs["billing"]["gst_amount_inr"].round(2) != expected_gst)

incorrect_gst_actual = incorrect_gst_mask.sum()

incorrect_gst_actual

np.int64(1150)

In [88]:
#its not matching ,inspecting the flag


gst_check = all_dfs["billing"][
    ["invoice_id", "base_amount_inr", "gst_amount_inr"]].copy()

gst_check["expected_gst"] = expected_gst

gst_check["difference"] = (
    gst_check["gst_amount_inr"] - gst_check["expected_gst"]).round(2)

gst_check[incorrect_gst_mask].head(10)

,invoice_id,base_amount_inr,gst_amount_inr,expected_gst,difference
155,INV00000156,1065.44,121.51,191.78,-70.27
209,INV00000210,1011.24,141.37,182.02,-40.65
255,INV00000256,504.42,35.10,90.80,-55.70
463,INV00000464,1059.72,145.90,190.75,-44.85
473,INV00000474,90.39,16.76,16.27,0.49
674,INV00000675,8071.35,1873.71,1452.84,420.87
698,INV00000699,1005.08,238.05,180.91,57.14
1097,INV00001098,665.77,34.36,119.84,-85.48
1168,INV00001169,618.68,111.44,111.36,0.08
1352,INV00001353,518.85,123.12,93.39,29.73


In [89]:
#checking whether a duplicated invoice caused the 1,150 vs 1,149 difference


incorrect_gst_unique_invoices = gst_check.loc[
    incorrect_gst_mask,
    "invoice_id"].nunique()

print("Flagged rows:", incorrect_gst_actual)
print("Unique flagged invoices:", incorrect_gst_unique_invoices)

Flagged rows: 1150
Unique flagged invoices: 1149


In [90]:
# recording incorrect gst

data_quality_comparison.loc[
    data_quality_comparison["issue_type"] == "incorrect_gst",
    "actual_rows_affected"] = incorrect_gst_unique_invoices

data_quality_comparison[
    data_quality_comparison["issue_type"] == "incorrect_gst"]

data_quality_comparison.head(12)

,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286
5,customers,incorrect_pin,190,191
6,customers,misspelled_city,380,380
7,customers,inconsistent_capitalisation,570,571
8,customers,impossible_age,38,38
9,customers,mixed_date_format,380,383


In [91]:
#verifing the negative invoice count


negative_invoice_actual = (
    all_dfs["billing"]["total_amount_inr"] < 0).sum()

negative_invoice_actual

np.int64(229)

In [92]:
#recording negative invoice issue

data_quality_comparison.loc[
    data_quality_comparison["issue_type"] == "negative_invoice_amount",
    "actual_rows_affected"] = negative_invoice_actual

data_quality_comparison[
    data_quality_comparison["issue_type"] == "negative_invoice_amount"]

data_quality_comparison.head(13)

,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286
5,customers,incorrect_pin,190,191
6,customers,misspelled_city,380,380
7,customers,inconsistent_capitalisation,570,571
8,customers,impossible_age,38,38
9,customers,mixed_date_format,380,383


In [93]:
#checking the billing date range


parsed_billing_dates = pd.to_datetime(
    all_dfs["billing"]["billing_date"],format="%d-%m-%Y",errors="coerce")

print("Earliest billing date:", parsed_billing_dates.min())
print("Latest billing date:", parsed_billing_dates.max())

Earliest billing date: 2014-02-01 00:00:00
Latest billing date: 2027-04-28 00:00:00


In [94]:
#counting billing dates later than today


reference_date = pd.Timestamp.today().normalize()

future_date_mask = parsed_billing_dates > reference_date

future_dates_actual = future_date_mask.sum()

print("Reference date:", reference_date)
print("Future billing dates:", future_dates_actual)

Reference date: 2026-09-08 00:00:00
Future billing dates: 132


In [95]:
#checking how many billing dates occur in each year


billing_year_counts = (
    parsed_billing_dates.dt.year.value_counts().sort_index())

billing_year_counts.tail()

billing_date
2023     2218
2024     3482
2025    77055
2026    25708
2027       67
Name: count, dtype: int64

In [96]:
#the fixed project cutoff of 31 March 2026

project_cutoff_date = pd.Timestamp("2026-03-31")

future_date_mask = parsed_billing_dates > project_cutoff_date

future_dates_actual = future_date_mask.sum()

print("Project cutoff date:", project_cutoff_date)
print("Future billing dates:", future_dates_actual)

Project cutoff date: 2026-03-31 00:00:00
Future billing dates: 232


In [97]:
#count the unique future-dated invoices


future_unique_invoices = all_dfs["billing"].loc[
    future_date_mask,"invoice_id"].nunique()

print("Future-dated rows:", future_dates_actual)
print("Unique future-dated invoices:", future_unique_invoices)

Future-dated rows: 232
Unique future-dated invoices: 229


In [98]:
#recording unique-invoice count

data_quality_comparison.loc[
    data_quality_comparison["issue_type"] == "future_dates",
    "actual_rows_affected"] = future_unique_invoices

data_quality_comparison[data_quality_comparison["issue_type"] == "future_dates"]

data_quality_comparison.head(14)

,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286
5,customers,incorrect_pin,190,191
6,customers,misspelled_city,380,380
7,customers,inconsistent_capitalisation,570,571
8,customers,impossible_age,38,38
9,customers,mixed_date_format,380,383


In [99]:
#Recording the duplicate invoice

data_quality_comparison.loc[
    data_quality_comparison["issue_type"] == "duplicate_invoices",
    "actual_rows_affected"] = duplicate_billing_rows

data_quality_comparison[
    data_quality_comparison["issue_type"] == "duplicate_invoices"]

data_quality_comparison.head(15)

,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286
5,customers,incorrect_pin,190,191
6,customers,misspelled_city,380,380
7,customers,inconsistent_capitalisation,570,571
8,customers,impossible_age,38,38
9,customers,mixed_date_format,380,383


In [100]:
all_dfs["data_quality_issue_log"]

,table,issue_type,rows_affected
0,customers,missing_email,760
1,customers,missing_address,380
2,customers,missing_income,950
3,customers,invalid_phone,228
4,customers,invalid_email,285
5,customers,incorrect_pin,190
6,customers,misspelled_city,380
7,customers,inconsistent_capitalisation,570
8,customers,impossible_age,38
9,customers,mixed_date_format,380


In [101]:
# payment broken foreign key


broken_payment_fk_mask = ~all_dfs["payments"]["invoice_id"].isin(
    all_dfs["billing"]["invoice_id"])

broken_payment_fk_rows = broken_payment_fk_mask.sum()
broken_payment_fk_rows

np.int64(184)

In [102]:
#recording the broken foreign key count


data_quality_comparison.loc[data_quality_comparison["issue_type"] == "broken_foreign_key",
"actual_rows_affected"] = broken_payment_fk_rows

data_quality_comparison[data_quality_comparison["issue_type"]== "broken_foreign_key"]


data_quality_comparison.head(16)


,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286
5,customers,incorrect_pin,190,191
6,customers,misspelled_city,380,380
7,customers,inconsistent_capitalisation,570,571
8,customers,impossible_age,38,38
9,customers,mixed_date_format,380,383


In [103]:
#duplicate payments


data_quality_comparison.loc[data_quality_comparison["issue_type"] == "duplicate_payments",
"actual_rows_affected"] = duplicate_payment_rows
data_quality_comparison[data_quality_comparison["issue_type"] == "duplicate_payments"]


data_quality_comparison.head(17)



,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286
5,customers,incorrect_pin,190,191
6,customers,misspelled_city,380,380
7,customers,inconsistent_capitalisation,570,571
8,customers,impossible_age,38,38
9,customers,mixed_date_format,380,383


In [104]:
# subscription table # null_foreign_key


null_foreign_key_actual = (
    all_dfs["subscriptions"]["plan_id"].isna().sum())

null_foreign_key_actual

np.int64(41)

In [105]:
#recording the null_foreign_key

data_quality_comparison.loc[
    data_quality_comparison["issue_type"] == "null_foreign_key",
    "actual_rows_affected"] = null_foreign_key_actual

data_quality_comparison[
    data_quality_comparison["issue_type"] == "null_foreign_key"]

data_quality_comparison.head(18)





,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286
5,customers,incorrect_pin,190,191
6,customers,misspelled_city,380,380
7,customers,inconsistent_capitalisation,570,571
8,customers,impossible_age,38,38
9,customers,mixed_date_format,380,383


In [106]:
all_dfs["subscriptions"].columns.tolist()

['subscription_id',
 'customer_id',
 'plan_id',
 'start_date',
 'end_date',
 'billing_cycle',
 'monthly_charge_inr',
 'subscription_status']

In [107]:
print("Billing cycle values:")
print(
    all_dfs["subscriptions"]["billing_cycle"]
    .value_counts(dropna=False))

print("\nSubscription status values:")
print(
    all_dfs["subscriptions"]["subscription_status"]
    .value_counts(dropna=False))

Billing cycle values:
billing_cycle
Monthly    15107
Annual      5416
Name: count, dtype: int64

Subscription status values:
subscription_status
Active           16930
Terminated        3491
UNKNOWN_STATE      102
Name: count, dtype: int64


In [108]:
valid_subscription_statuses = ["Active", "Terminated"]

invalid_category_mask = ~all_dfs["subscriptions"][
    "subscription_status"
].isin(valid_subscription_statuses)

invalid_category_actual = invalid_category_mask.sum()

invalid_category_actual


np.int64(102)

In [109]:
#recording

data_quality_comparison.loc[
    data_quality_comparison["issue_type"] == "invalid_category",
    "actual_rows_affected"] = invalid_category_actual

data_quality_comparison[
    data_quality_comparison["issue_type"] == "invalid_category"]

data_quality_comparison.head(19)


,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286
5,customers,incorrect_pin,190,191
6,customers,misspelled_city,380,380
7,customers,inconsistent_capitalisation,570,571
8,customers,impossible_age,38,38
9,customers,mixed_date_format,380,383


In [110]:
all_dfs["data_quality_issue_log"].head

<bound method NDFrame.head of             table                   issue_type  rows_affected
0       customers                missing_email            760
1       customers              missing_address            380
2       customers               missing_income            950
3       customers                invalid_phone            228
4       customers                invalid_email            285
5       customers                incorrect_pin            190
6       customers              misspelled_city            380
7       customers  inconsistent_capitalisation            570
8       customers               impossible_age             38
9       customers            mixed_date_format            380
10      customers          duplicate_customers             76
11        billing                incorrect_gst           1149
12        billing      negative_invoice_amount            229
13        billing                 future_dates            229
14        billing           duplicate_in

In [111]:
#usage_data outlier values
#upper end

all_dfs["usage_data"]["data_gb_used"].describe(
    percentiles=[0.95, 0.99, 0.995, 0.997, 0.999])




count    57000.000000
mean        40.184885
std        332.574130
min          0.240000
50%         19.140000
95%         79.080000
99%        140.670900
99.5%      179.021250
99.7%      345.752460
99.9%     4331.530484
max      22172.700708
Name: data_gb_used, dtype: float64

In [112]:
#around the boundary

sorted_usage = (
    all_dfs["usage_data"]["data_gb_used"]
    .sort_values(ascending=False)
    .reset_index(drop=True))

sorted_usage.iloc[165:176]

165    544.661710
166    497.511359
167    437.824105
168    371.730000
169    369.990918
170    356.540000
171    345.720000
172    307.643341
173    298.130000
174    292.960000
175    286.860000
Name: data_gb_used, dtype: float64

In [113]:
#Test the inferred extreme-usage threshold


extreme_usage_threshold = 350

outlier_values_mask = (
    all_dfs["usage_data"]["data_gb_used"] > extreme_usage_threshold)

outlier_values_actual = outlier_values_mask.sum()

outlier_values_actual

np.int64(171)

In [114]:
#recording the final issue

data_quality_comparison.loc[
    data_quality_comparison["issue_type"] == "outlier_values",
    "actual_rows_affected"] = outlier_values_actual

data_quality_comparison[
    data_quality_comparison["issue_type"] == "outlier_values"]


data_quality_comparison.head(20)

,table,issue_type,expected_rows_affected,actual_rows_affected
0,customers,missing_email,760,745
1,customers,missing_address,380,380
2,customers,missing_income,950,954
3,customers,invalid_phone,228,228
4,customers,invalid_email,285,286
5,customers,incorrect_pin,190,191
6,customers,misspelled_city,380,380
7,customers,inconsistent_capitalisation,570,571
8,customers,impossible_age,38,38
9,customers,mixed_date_format,380,383


In [115]:
#Verifying that no actual result is missing

missing_actual_results = (
    data_quality_comparison["actual_rows_affected"].isna().sum())

missing_actual_results


np.int64(0)

In [116]:
#calculating the difference and match status


data_quality_comparison["actual_rows_affected"] = (
    data_quality_comparison["actual_rows_affected"].astype(int))

data_quality_comparison["difference"] = (
    data_quality_comparison["actual_rows_affected"]
    - data_quality_comparison["expected_rows_affected"])

data_quality_comparison["comparison_status"] = (
    data_quality_comparison["difference"]
    .eq(0)
    .map({True: "Matched", False: "Different"}))

data_quality_comparison

,table,issue_type,expected_rows_affected,actual_rows_affected,difference,comparison_status
0,customers,missing_email,760,745,-15,Different
1,customers,missing_address,380,380,0,Matched
2,customers,missing_income,950,954,4,Different
3,customers,invalid_phone,228,228,0,Matched
4,customers,invalid_email,285,286,1,Different
5,customers,incorrect_pin,190,191,1,Different
6,customers,misspelled_city,380,380,0,Matched
7,customers,inconsistent_capitalisation,570,571,1,Different
8,customers,impossible_age,38,38,0,Matched
9,customers,mixed_date_format,380,383,3,Different


In [117]:
comparison_summary = (
    data_quality_comparison["comparison_status"]
    .value_counts())

comparison_summary

comparison_status
Matched      14
Different     6
Name: count, dtype: int64

In [118]:
different_issues = data_quality_comparison.loc[
    data_quality_comparison["comparison_status"] == "Different",
    [
        "table",
        "issue_type",
        "expected_rows_affected",
        "actual_rows_affected",
        "difference"]].reset_index(drop=True)

different_issues

,table,issue_type,expected_rows_affected,actual_rows_affected,difference
0,customers,missing_email,760,745,-15
1,customers,missing_income,950,954,4
2,customers,invalid_email,285,286,1
3,customers,incorrect_pin,190,191,1
4,customers,inconsistent_capitalisation,570,571,1
5,customers,mixed_date_format,380,383,3


# NexaTel Customer Churn – Phase 1 Data Quality Report

## Executive Summary

The data-quality assessment covered 24 source tables and validated 20 issues recorded in `data_quality_issue_log.csv`. Out of 20 checks, 14 matched the expected results and 6 showed differences, giving an exact-match rate of 70%. All six differences were found in the customers table.

## Key Findings

- Missing values were identified in important customer fields, including 745 missing emails, 380 missing addresses and 954 missing annual-income values.
- Duplicate records were found in customers (76), billing (344) and payments (276).
- Customer foreign keys were valid across subscriptions, billing and usage data. However, 184 payment records contained invoice IDs that were not available in billing.
- Billing validation identified 1,149 unique invoices with incorrect GST, 229 negative invoices and 229 future-dated invoices.
- Subscriptions contained 41 missing plan IDs and 102 invalid subscription-status values.
- A total of 171 extreme usage records exceeded the inferred threshold of 350 GB.

## Differences From the Issue Log

| Issue | Expected | Actual | Difference |
|---|---:|---:|---:|
| Missing email | 760 | 745 | -15 |
| Missing income | 950 | 954 | +4 |
| Invalid email | 285 | 286 | +1 |
| Incorrect PIN | 190 | 191 | +1 |
| Inconsistent capitalisation | 570 | 571 | +1 |
| Mixed date format | 380 | 383 | +3 |

## Recommendations

1. Update the six counts in the issue log and clearly document each validation rule.
2. Remove or investigate duplicate customer, billing and payment records.
3. Standardise email, PIN, city-name and date formats before analysis.
4. Automate checks for primary keys, foreign keys, GST calculations, allowed categories and future dates.
5. Confirm the 350 GB usage threshold with the business team before treating these records as outliers.

## Assumptions

GST and future-date issues were counted at the unique-invoice level. Future dates were validated using 31 March 2026 as the project cutoff. The 350 GB usage threshold was inferred from the data and requires business confirmation.

In [119]:
# specific check 

#billing


billing = all_dfs["billing"].copy()

# Define the fixed project cutoff date
project_cutoff = pd.Timestamp("2026-03-31")

billing["billing_date"] = pd.to_datetime(
    billing["billing_date"],
    errors="coerce")

billing["total_amount_inr"] = pd.to_numeric(
    billing["total_amount_inr"],
    errors="coerce")



# Future billing dates
future_billing_mask = billing["billing_date"] > project_cutoff

# Negative invoice amounts
negative_amount_mask = billing["total_amount_inr"] < 0

print("Future billing rows:", future_billing_mask.sum())
print(
    "Unique future invoices:",
    billing.loc[future_billing_mask, "invoice_id"].nunique())

print("Negative billing rows:", negative_amount_mask.sum())
print(
    "Unique negative invoices:",
    billing.loc[negative_amount_mask, "invoice_id"].nunique())

Future billing rows: 232
Unique future invoices: 229
Negative billing rows: 229
Unique negative invoices: 229


C:\Users\Dell\AppData\Local\Temp\ipykernel_15016\3967918523.py:11: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  billing["billing_date"] = pd.to_datetime(


In [120]:
#customers check


customers = all_dfs["customers"].copy()

# Impossible ages
customer_age = pd.to_numeric(
    customers["age"],
    errors="coerce")

impossible_age_mask = (
    (customer_age < 0) |
    (customer_age > 120))

# Invalid PIN codes
pin_text = (
    customers["pin_code"]
    .astype("string")
    .str.strip())

valid_pin_mask = pin_text.str.fullmatch(r"\d{6}").fillna(False)
invalid_pin_mask = ~valid_pin_mask

# Invalid phone numbers
phone_text = (
    customers["phone_number"]
    .astype("string")
    .str.strip())

valid_phone_mask = phone_text.str.fullmatch(r"91\d{10}").fillna(False)
invalid_phone_mask = ~valid_phone_mask

print("Impossible ages:", impossible_age_mask.sum())
print("Invalid PIN codes:", invalid_pin_mask.sum())
print("Invalid phone numbers:", invalid_phone_mask.sum())

Impossible ages: 23
Invalid PIN codes: 191
Invalid phone numbers: 228


In [121]:
# payment foreign key check


payments = all_dfs["payments"].copy()

broken_payment_fk_mask = ~payments["invoice_id"].isin(
    billing["invoice_id"])

broken_payment_rows = broken_payment_fk_mask.sum()

print("Payments with broken invoice IDs:", broken_payment_rows)

Payments with broken invoice IDs: 184


In [122]:
#Unresolved complaint percentage

all_dfs["complaints"].columns.tolist()



['complaint_id',
 'customer_id',
 'complaint_date',
 'complaint_type',
 'severity',
 'status',
 'resolution_date']

In [123]:
complaints = all_dfs["complaints"].copy()

# Missing or blank resolution dates
resolution_text = (
    complaints["resolution_date"]
    .astype("string")
    .str.strip())

unresolved_mask = (
    complaints["resolution_date"].isna() |
    resolution_text.eq(""))

unresolved_count = unresolved_mask.sum()

unresolved_share = (unresolved_count / len(complaints)) * 100

print("Total complaints:", len(complaints))
print("Unresolved complaints:", unresolved_count)
print(f"Unresolved complaint share: {unresolved_share:.2f}%")

Total complaints: 16584
Unresolved complaints: 7348
Unresolved complaint share: 44.31%


In [124]:
#Subscription checks


subscriptions = all_dfs["subscriptions"].copy()

# Null foreign key
null_plan_mask = subscriptions["plan_id"].isna()

# Invalid subscription status
valid_statuses = ["Active", "Terminated"]

subscription_status = (
    subscriptions["subscription_status"]
    .astype("string")
    .str.strip())

invalid_status_mask = ~subscription_status.isin(valid_statuses)

print("Rows with null plan_id:", null_plan_mask.sum())
print("Rows with invalid subscription status:", invalid_status_mask.sum())

Rows with null plan_id: 41
Rows with invalid subscription status: 102


In [125]:
# Creating clean data format


from pathlib import Path

clean_folder = Path(r"C:\Users\Dell\Nexatel_project\cleaned_data")
clean_folder.mkdir(exist_ok=True)

print(clean_folder)

C:\Users\Dell\Nexatel_project\cleaned_data


In [127]:
print(all_dfs["customers"].columns.tolist())

['customer_id', 'first_name', 'last_name', 'gender', 'date_of_birth', 'age', 'email', 'phone_number', 'address', 'city_id', 'city_name', 'state_id', 'pin_code', 'city_tier', 'region_id', 'occupation', 'annual_income_inr', 'customer_segment', 'product_line', 'plan_id', 'acquisition_channel', 'acquisition_date', 'tenure_months', 'customer_status', 'churn_date']


In [137]:
customer_columns = [
    "customer_id", "gender", "age", "city_id", "city_name",
    "state_id", "city_tier", "region_id", "occupation",
    "annual_income_inr", "customer_segment", "product_line",
    "plan_id", "acquisition_channel", "acquisition_date",
    "tenure_months", "customer_status", "churn_date"]
    
customers_clean = all_dfs["customers"][customer_columns].copy()


#remove duplicates as we already inspected it

customers_clean = customers_clean.drop_duplicates(subset="customer_id",keep="first")

#Convert age to numeric and replace impossible ages with missing values

customers_clean["age"] = pd.to_numeric(customers_clean["age"],errors="coerce").astype("Float64")

customers_clean.loc[~customers_clean["age"].between(0,120),"age"]=pd.NA

#CONVERT DATES

customers_clean["acquisition_date"] = pd.to_datetime(
    customers_clean["acquisition_date"],
    dayfirst=True,
    errors="coerce")

customers_clean["churn_date"] = pd.to_datetime(
    customers_clean["churn_date"],
    dayfirst=True,
    errors="coerce")

# Export the cleaned table

customers_clean.to_csv(clean_folder / "customers_clean.csv",index=False)

print("Clean customer rows:", len(customers_clean))
print("Duplicate customer IDs:", customers_clean["customer_id"].duplicated().sum())
print("Invalid ages:", (~customers_clean["age"].between(0, 120)).sum())
print("File saved: customers_clean.csv")

Clean customer rows: 19000
Duplicate customer IDs: 0
Invalid ages: 0
File saved: customers_clean.csv


In [138]:
#subscription check

print(all_dfs["subscriptions"].columns.tolist())

['subscription_id', 'customer_id', 'plan_id', 'start_date', 'end_date', 'billing_cycle', 'monthly_charge_inr', 'subscription_status']


In [139]:
#Cleaning and exporting subscriptions


subscriptions_clean = all_dfs["subscriptions"].copy()

# Clean ID and category columns
text_columns = [
    "subscription_id", "customer_id", "plan_id",
    "billing_cycle", "subscription_status"]

for column in text_columns:
    subscriptions_clean[column] = (
        subscriptions_clean[column]
        .astype("string")
        .str.strip())

# Handle missing plan IDs
subscriptions_clean["plan_id"] = (
    subscriptions_clean["plan_id"]
    .replace("", pd.NA)
    .fillna("UNKNOWN"))

# Standardize subscription status
subscriptions_clean["subscription_status"] = (
    subscriptions_clean["subscription_status"].str.title())

valid_statuses = ["Active", "Terminated"]

subscriptions_clean.loc[
    ~subscriptions_clean["subscription_status"].isin(valid_statuses),
    "subscription_status"] = "Unknown"

# Correct data types
subscriptions_clean["start_date"] = pd.to_datetime(
    subscriptions_clean["start_date"],
    dayfirst=True,
    errors="coerce")

subscriptions_clean["end_date"] = pd.to_datetime(
    subscriptions_clean["end_date"],
    dayfirst=True,
    errors="coerce")

subscriptions_clean["monthly_charge_inr"] = pd.to_numeric(
    subscriptions_clean["monthly_charge_inr"],
    errors="coerce")

# Export
subscriptions_clean.to_csv(
    clean_folder / "subscriptions_clean.csv",
    index=False)

print("Clean subscription rows:", len(subscriptions_clean))
print("Unknown plan IDs:", (subscriptions_clean["plan_id"] == "UNKNOWN").sum())
print("Unknown statuses:", (subscriptions_clean["subscription_status"] == "Unknown").sum())
print("File saved: subscriptions_clean.csv")

Clean subscription rows: 20523
Unknown plan IDs: 41
Unknown statuses: 102
File saved: subscriptions_clean.csv


In [140]:
# checking plans table


print(all_dfs["plans"].columns.tolist())

['plan_id', 'plan_name', 'product_line', 'billing_cycle', 'monthly_charge', 'data_quota_gb', 'voice_minutes', 'sms_count', 'segment', 'is_active']


In [141]:
#cleaning and exporting plans table

plans_clean = all_dfs["plans"].copy()

# Clean text columns
plan_text_columns = [
    "plan_id", "plan_name", "product_line",
    "billing_cycle", "segment"
]

for column in plan_text_columns:
    plans_clean[column] = (
        plans_clean[column]
        .astype("string")
        .str.strip()
    )

# Convert numeric columns
plan_numeric_columns = [
    "monthly_charge", "data_quota_gb",
    "voice_minutes", "sms_count"]

for column in plan_numeric_columns:
    plans_clean[column] = pd.to_numeric(
        plans_clean[column],
        errors="coerce")

# Keep one row per plan
plans_clean = plans_clean.drop_duplicates(
    subset="plan_id",
    keep="first")

# Add a matching record for unknown plan IDs
unknown_plan = pd.DataFrame([{
    "plan_id": "UNKNOWN",
    "plan_name": "Unknown Plan",
    "product_line": "Unknown",
    "billing_cycle": "Unknown",
    "monthly_charge": pd.NA,
    "data_quota_gb": pd.NA,
    "voice_minutes": pd.NA,
    "sms_count": pd.NA,
    "segment": "Unknown",
    "is_active": False}])

plans_clean = pd.concat(
    [plans_clean, unknown_plan],
    ignore_index=True)

# Export
plans_clean.to_csv(
    clean_folder / "plans_clean.csv",
    index=False)

print("Clean plan rows:", len(plans_clean))
print("Duplicate plan IDs:", plans_clean["plan_id"].duplicated().sum())
print("Unknown plan rows:", (plans_clean["plan_id"] == "UNKNOWN").sum())
print("File saved: plans_clean.csv")

Clean plan rows: 26
Duplicate plan IDs: 0
Unknown plan rows: 1
File saved: plans_clean.csv


In [142]:
# checking billing table

print(all_dfs["billing"].columns.tolist())

['invoice_id', 'customer_id', 'billing_date', 'billing_period_month', 'base_amount_inr', 'gst_amount_inr', 'total_amount_inr', 'due_date', 'payment_status', 'negative_amount_flag']


In [143]:
#cleaning and exporting billing 

billing_clean = all_dfs["billing"].copy()

# Clean ID and category columns
for column in ["invoice_id", "customer_id", "payment_status"]:
    billing_clean[column] = (
        billing_clean[column]
        .astype("string")
        .str.strip())

# Convert date columns
for column in ["billing_date", "due_date"]:
    billing_clean[column] = pd.to_datetime(
        billing_clean[column],
        dayfirst=True,
        errors="coerce")

billing_clean["billing_period_month"] = pd.to_datetime(
    billing_clean["billing_period_month"],
    errors="coerce")

# Convert amount columns
amount_columns = [
    "base_amount_inr",
    "gst_amount_inr",
    "total_amount_inr"]

for column in amount_columns:
    billing_clean[column] = pd.to_numeric(
        billing_clean[column],
        errors="coerce")

# Record the Phase 1 issue counts before cleaning
duplicate_invoices = billing_clean["invoice_id"].duplicated().sum()

today = pd.Timestamp.today().normalize()
future_mask = billing_clean["billing_date"] > today
negative_mask = billing_clean["total_amount_inr"] < 0

future_bills = future_mask.sum()
negative_bills = negative_mask.sum()

# Apply cleaning rules
billing_clean = billing_clean.drop_duplicates(
    subset="invoice_id",
    keep="first")

billing_clean = billing_clean[
    (billing_clean["billing_date"] <= today) &
    (billing_clean["total_amount_inr"] >= 0)].copy()

# Export
billing_clean.to_csv(
    clean_folder / "billing_clean.csv",
    index=False)

print("Clean billing rows:", len(billing_clean))
print("Duplicate invoices removed:", duplicate_invoices)
print("Future bills excluded:", future_bills)
print("Negative bills excluded:", negative_bills)
print("File saved: billing_clean.csv")

C:\Users\Dell\AppData\Local\Temp\ipykernel_15016\1937361747.py:21: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  billing_clean["billing_period_month"] = pd.to_datetime(


Clean billing rows: 114609
Duplicate invoices removed: 344
Future bills excluded: 132
Negative bills excluded: 229
File saved: billing_clean.csv


In [144]:
print("Unparsed billing months:",
    billing_clean["billing_period_month"].isna().sum())

print(billing_clean["billing_period_month"].head())

Unparsed billing months: 0
0   2026-03-01
1   2026-03-01
2   2026-01-01
3   2025-12-01
4   2025-12-01
Name: billing_period_month, dtype: datetime64[ns]


In [145]:
#checking support tickets & complaints


print("SUPPORT TICKETS:")
print(all_dfs["support_tickets"].columns.tolist())

print("\nCOMPLAINTS:")
print(all_dfs["complaints"].columns.tolist())

SUPPORT TICKETS:
['ticket_id', 'customer_id', 'created_date', 'category', 'priority', 'channel', 'status', 'first_contact_resolution', 'assigned_employee_id', 'resolution_hours', 'resolution_date']

COMPLAINTS:
['complaint_id', 'customer_id', 'complaint_date', 'complaint_type', 'severity', 'status', 'resolution_date']


In [146]:
#clean and exporting support tickets

support_clean = all_dfs["support_tickets"].copy()

# Clean identifier and category columns
text_columns = [
    "ticket_id", "customer_id", "category",
    "priority", "channel", "status",
    "assigned_employee_id"
]

for column in text_columns:
    support_clean[column] = (
        support_clean[column]
        .astype("string")
        .str.strip()
    )

# Standardize selected category values
for column in ["priority", "channel", "status"]:
    support_clean[column] = support_clean[column].str.title()

# Convert First Contact Resolution to True/False
fcr_values = (
    support_clean["first_contact_resolution"]
    .astype("string")
    .str.strip()
    .str.lower()
)

support_clean["first_contact_resolution"] = fcr_values.map({
    "yes": True,
    "no": False,
    "true": True,
    "false": False,
    "1": True,
    "0": False
}).astype("boolean")

# Convert resolution hours to numeric
support_clean["resolution_hours"] = pd.to_numeric(
    support_clean["resolution_hours"],
    errors="coerce"
)

# Convert dates
for column in ["created_date", "resolution_date"]:
    support_clean[column] = pd.to_datetime(
        support_clean[column],
        dayfirst=True,
        errors="coerce"
    )

# Remove repeated ticket IDs
duplicate_tickets = support_clean["ticket_id"].duplicated().sum()

support_clean = support_clean.drop_duplicates(
    subset="ticket_id",
    keep="first"
)

# Export
support_clean.to_csv(
    clean_folder / "support_tickets_clean.csv",
    index=False
)

print("Clean support-ticket rows:", len(support_clean))
print("Duplicate ticket IDs removed:", duplicate_tickets)
print(
    "Missing/unrecognized FCR values:",
    support_clean["first_contact_resolution"].isna().sum()
)
print("File saved: support_tickets_clean.csv")

Clean support-ticket rows: 31490
Duplicate ticket IDs removed: 0
Missing/unrecognized FCR values: 0
File saved: support_tickets_clean.csv


In [147]:
# cleaning and exporting complaints

complaints_clean = all_dfs["complaints"].copy()

# Clean text columns
complaint_text_columns = [
    "complaint_id", "customer_id",
    "complaint_type", "severity", "status"
]

for column in complaint_text_columns:
    complaints_clean[column] = (
        complaints_clean[column]
        .astype("string")
        .str.strip()
    )

# Standardize category formatting
complaints_clean["severity"] = (
    complaints_clean["severity"].str.title()
)

complaints_clean["status"] = (
    complaints_clean["status"].str.title()
)

# Convert dates
for column in ["complaint_date", "resolution_date"]:
    complaints_clean[column] = pd.to_datetime(
        complaints_clean[column],
        dayfirst=True,
        errors="coerce"
    )

# Remove repeated complaint IDs
duplicate_complaints = (
    complaints_clean["complaint_id"].duplicated().sum()
)

complaints_clean = complaints_clean.drop_duplicates(
    subset="complaint_id",
    keep="first"
)

# Calculate unresolved share after cleaning
unresolved_share_clean = (
    complaints_clean["status"].eq("Unresolved").mean() * 100
)

# Export
complaints_clean.to_csv(
    clean_folder / "complaints_clean.csv",
    index=False
)

print("Clean complaint rows:", len(complaints_clean))
print("Duplicate complaint IDs removed:", duplicate_complaints)
print(f"Unresolved complaint share: {unresolved_share_clean:.2f}%")
print("File saved: complaints_clean.csv")

Clean complaint rows: 16584
Duplicate complaint IDs removed: 0
Unresolved complaint share: 44.31%
File saved: complaints_clean.csv


In [148]:
#Checking network and geography columns


for table in ["network_quality", "cities", "states", "regions"]:
    print(f"\n{table.upper()}:")
    print(all_dfs[table].columns.tolist())


NETWORK_QUALITY:
['record_id', 'customer_id', 'city_id', 'month', 'avg_signal_strength_dbm', 'dropped_call_rate_pct', 'avg_download_speed_mbps', 'network_downtime_hours']

CITIES:
['city_id', 'city_name', 'state_id', 'state_name', 'zone', 'region_id', 'tier', 'pin_prefix']

STATES:
['state_id', 'state_name', 'state_code', 'zone']

REGIONS:
['region_id', 'region_name', 'zone_hq_city']


In [149]:
#cleaning and exporting geography tables


cities_clean = all_dfs["cities"].copy()
states_lookup = all_dfs["states"].copy()
regions_lookup = all_dfs["regions"].copy()

# Clean all geography text columns
for dataframe in [cities_clean, states_lookup, regions_lookup]:
    for column in dataframe.select_dtypes(
        include=["object", "string"]
    ).columns:
        dataframe[column] = (
            dataframe[column]
            .astype("string")
            .str.strip()
        )

# Keep unique geography IDs
cities_clean = cities_clean.drop_duplicates(
    subset="city_id",
    keep="first"
)

states_lookup = states_lookup.drop_duplicates(
    subset="state_id",
    keep="first"
)

regions_lookup = regions_lookup.drop_duplicates(
    subset="region_id",
    keep="first"
)

# Add state code to cities
geography_clean = cities_clean.merge(
    states_lookup[["state_id", "state_code"]],
    on="state_id",
    how="left"
)

# Add region details
geography_clean = geography_clean.merge(
    regions_lookup[
        ["region_id", "region_name", "zone_hq_city"]
    ],
    on="region_id",
    how="left"
)

# Help Power BI identify Indian map locations
geography_clean["country"] = "India"

# Export
geography_clean.to_csv(
    clean_folder / "geography_clean.csv",
    index=False
)

print("Geography rows:", len(geography_clean))
print(
    "Duplicate city IDs:",
    geography_clean["city_id"].duplicated().sum()
)
print(
    "Missing region names:",
    geography_clean["region_name"].isna().sum()
)
print("File saved: geography_clean.csv")

Geography rows: 68
Duplicate city IDs: 0
Missing region names: 0
File saved: geography_clean.csv


In [150]:
#cleaning and exporting network quality data

network_clean = all_dfs["network_quality"].copy()

# Clean identifier columns
for column in ["record_id", "customer_id", "city_id"]:
    network_clean[column] = (
        network_clean[column]
        .astype("string")
        .str.strip()
    )

# Convert month into a date
network_clean["month"] = pd.to_datetime(
    network_clean["month"],
    errors="coerce"
)

# Convert network measurements to numbers
network_metrics = [
    "avg_signal_strength_dbm",
    "dropped_call_rate_pct",
    "avg_download_speed_mbps",
    "network_downtime_hours"
]

for column in network_metrics:
    network_clean[column] = pd.to_numeric(
        network_clean[column],
        errors="coerce"
    )

# Remove repeated record IDs
duplicate_network_records = (
    network_clean["record_id"].duplicated().sum()
)

network_clean = network_clean.drop_duplicates(
    subset="record_id",
    keep="first"
)

# Export
network_clean.to_csv(
    clean_folder / "network_quality_clean.csv",
    index=False
)

print("Clean network rows:", len(network_clean))
print(
    "Duplicate network records removed:",
    duplicate_network_records
)
print("Unparsed months:", network_clean["month"].isna().sum())
print("File saved: network_quality_clean.csv")

C:\Users\Dell\AppData\Local\Temp\ipykernel_15016\3913605702.py:14: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  network_clean["month"] = pd.to_datetime(


Clean network rows: 57000
Duplicate network records removed: 0
Unparsed months: 0
File saved: network_quality_clean.csv


In [151]:
#Check retention-campaign columns


print(all_dfs["retention_campaigns"].columns.tolist())

['campaign_id', 'customer_id', 'campaign_name', 'offer_type', 'contact_date', 'channel', 'response', 'retained_flag']


In [152]:
#Clean and export retention campaigns

retention_clean = all_dfs["retention_campaigns"].copy()

# Clean text columns
retention_text_columns = [
    "campaign_id", "customer_id", "campaign_name",
    "offer_type", "channel", "response"]

for column in retention_text_columns:
    retention_clean[column] = (
        retention_clean[column]
        .astype("string")
        .str.strip())

# Standardize category formatting
for column in ["offer_type", "channel", "response"]:
    retention_clean[column] = (
        retention_clean[column].str.title()
    )

# Convert contact date
retention_clean["contact_date"] = pd.to_datetime(
    retention_clean["contact_date"],
    dayfirst=True,
    errors="coerce")

# Convert retained flag to True/False
retained_values = (
    retention_clean["retained_flag"]
    .astype("string")
    .str.strip()
    .str.lower())

retention_clean["retained_flag"] = retained_values.map({
    "yes": True,
    "no": False,
    "true": True,
    "false": False,
    "1": True,
    "0": False,
    "y": True,
    "n": False}).astype("boolean")

# Remove only completely identical rows
exact_duplicates = retention_clean.duplicated().sum()
retention_clean = retention_clean.drop_duplicates()

# Export
retention_clean.to_csv(
    clean_folder / "retention_campaigns_clean.csv",
    index=False)

print("Clean campaign rows:", len(retention_clean))
print("Exact duplicate rows removed:", exact_duplicates)
print(
    "Missing/unrecognized retained flags:",
    retention_clean["retained_flag"].isna().sum())
print("Unparsed contact dates:", retention_clean["contact_date"].isna().sum())
print("File saved: retention_campaigns_clean.csv")

Clean campaign rows: 6475
Exact duplicate rows removed: 0
Missing/unrecognized retained flags: 0
Unparsed contact dates: 0
File saved: retention_campaigns_clean.csv


In [153]:
#Verifying the exported files

clean_files = sorted(
    file.name for file in clean_folder.glob("*.csv")
)

print("Clean files created:", len(clean_files))

for file in clean_files:
    print(file)

Clean files created: 9
billing_clean.csv
complaints_clean.csv
customers_clean.csv
geography_clean.csv
network_quality_clean.csv
plans_clean.csv
retention_campaigns_clean.csv
subscriptions_clean.csv
support_tickets_clean.csv
